films = [
    "The Shawshank Redemption",
    "The Godfather",
    "The Dark Knight",
    "The Lord of the Rings: The Return of the King",
    "Pulp Fiction",
    "Forrest Gump",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Fight Club",
    "Inception",
    "The Lord of the Rings: The Two Towers",
    "The Matrix",
    "Goodfellas",
    "The Godfather: Part II",
    "The Silence of the Lambs",
    "The Green Mile",
    "The Sixth Sense",
    "The Departed",
    "The Prestige",
    "The Lion King",
    "The Pianist",
    "The Truman Show",
    "The Shining",
    "The Exorcist",
    "The Terminator",
    "The Thing",
    "The Fly",
    "The Abyss",
    "The Lost",
    "The Island",
    "The Mist",
    "The Birds",
]

max_users = 30
directors = [
    "Steven Spielberg",
    "Martin Scorsese",
    "Clint Eastwood",
    "Woody Allen",
    "Spike Lee",
    "Quentin Tarantino",
    "Tim Burton",
    "David Fincher",
    "Christopher Nolan",
    "James Cameron",
]
genres = [
    "Action",
    "Adventure",
    "Animation",
    "Biography",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Family",
    "Fantasy",
    "Film-Noir",
    "History",
    "Horror",
    "Music",
    "Musical",
    "Mystery",
    "Romance",
    "Sci-Fi",
    "Sport",
    "Thriller",
    "War",
    "Western",
]
actors = [
    "Tom Hanks",
    "Leonardo DiCaprio",
    "Brad Pitt",
    "Johnny Depp",
    "Robert Downey Jr.",
    "Meryl Streep",
    "Jennifer Lawrence",
    "Scarlett Johansson",
    "Sandra Bullock",
    "Julia Roberts",
]
min_duration = 60
max_duration = 180
min_rating = 0
max_rating = 5
